jobs:
- job: Windows
  pool:
    vmImage: windows-latest
  steps:
  - template: compliance/compliance.yml
  - template: common/setup.yml
  - template: common/governance.yml   # Force governance before test to avoid false-positives.
  - template: common/build.yml

- job: Linux
  pool:
    vmImage: ubuntu-latest
  steps:
  - template: common/setup.yml
  - template: common/governance.yml   # Force governance before test to avoid false-positives.
  - template: common/publish-vsix.yml # Only publish vsix from linux build since we use this to release and want to stay consistent
  variables:
    Codeql.Enabled: $[in(variables['Build.Reason'], 'Schedule')] # Enable CodeQL only on scheduled builds because it is slow

- job: macOS
  pool:
    vmImage: macOS-latest
  steps:
  - template: common/setup.yml
  - template: common/governance.yml   # Force governance before test to avoid false-positives.
  - template: common/build.yml
    parameters:
      dockerUnavailable: 1 # Docker not available on MacOS agents (https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/docker)
